/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/data-processor": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search data processors
     * @description Search data processors by name, controller id, and status
     */
    get: operations["searchDataProcessors"];
    put?: never;
    /**
     * Create new data processor
     * @description Create a new data processor
     */
    post: operations["createDataProcessor"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/data-processor/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get data processor
     * @description Get a data processor by id
     */
    get: operations["getDataProcessor"];
    put?: never;
    post?: never;
    /**
     * Delete data processor
     * @description Delete a data processor by id
     */
    delete: operations["deleteDataProcessor"];
    options?: never;
    head?: never;
    /**
     * Update data processor
     * @description Update a data processor by id
     */
    patch: operations["updateDataProcessor"];
    trace?: never;
  };
  "/data-controller": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search data controllers
     * @description Search data controllers by name, controller id, and status
     */
    get: operations["searchDataControllers"];
    put?: never;
    /**
     * Create new data controller
     * @description Create a new data controller
     */
    post: operations["createDataController"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/data-controller/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get data controller
     * @description Get a data controller by id
     */
    get: operations["getDataController"];
    put?: never;
    post?: never;
    /**
     * Delete data controller
     * @description Delete a data controller by id
     */
    delete: operations["deleteDataController"];
    options?: never;
    head?: never;
    /**
     * Update data controller
     * @description Update a data controller by id
     */
    patch: operations["updateDataController"];
    trace?: never;
  };
  "/consent-purpose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search consent purposes
     * @description Search consent purposes by name, controllerId, purpose, retention days, and status
     */
    get: operations["searchConsentPurposes"];
    put?: never;
    /**
     * Create new consent purpose
     * @description Create a new consent purpose
     */
    post: operations["createConsentPurpose"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/consent-purpose/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get consent purpose
     * @description Get a consent purpose by id
     */
    get: operations["getConsentPurpose"];
    put?: never;
    post?: never;
    /**
     * Delete consent purpose
     * @description Delete a consent purpose by id
     */
    delete: operations["deleteConsentPurpose"];
    options?: never;
    head?: never;
    /**
     * Update consent purpose
     * @description Update a consent purpose by id
     */
    patch: operations["updateConsentPurpose"];
    trace?: never;
  };
  "/data-category": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search data categories
     * @description Search data categories by name, description, and status
     */
    get: operations["searchDataCategories"];
    put?: never;
    /**
     * Create new data category
     * @description Create a new data category
     */
    post: operations["createDataCategory"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/data-category/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get data category
     * @description Get a data category by id
     */
    get: operations["getDataCategory"];
    put?: never;
    post?: never;
    /**
     * Delete data category
     * @description Delete a data category by id
     */
    delete: operations["deleteDataCategory"];
    options?: never;
    head?: never;
    /**
     * Update data category
     * @description Update a data category by id
     */
    patch: operations["updateDataCategory"];
    trace?: never;
  };
  "/consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search consents
     * @description Search and filter consents with multiple criteria
     */
    get: operations["searchConsents"];
    put?: never;
    /**
     * Create consent
     * @description Create a new consent record
     */
    post: operations["createConsent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/consent/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get consent by ID
     * @description Get a consent by ID
     */
    get: operations["getConsent"];
    put?: never;
    post?: never;
    /**
     * Delete consent
     * @description Delete a consent by ID
     */
    delete: operations["deleteConsent"];
    options?: never;
    head?: never;
    /**
     * Update consent
     * @description Update an existing consent by id
     */
    patch: operations["updateConsent"];
    trace?: never;
  };
  "/consent-version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search consent versions
     * @description Search and filter consent versions with multiple criteria
     */
    get: operations["searchConsentVersions"];
    put?: never;
    /**
     * Create consent version
     * @description Create a new consent version record
     */
    post: operations["createConsentVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/consent-version/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get consent version by ID
     * @description Get a consent version by ID
     */
    get: operations["getConsentVersion"];
    put?: never;
    post?: never;
    /**
     * Delete consent version
     * @description Delete a consent version by ID
     */
    delete: operations["deleteConsentVersion"];
    options?: never;
    head?: never;
    /**
     * Update consent version
     * @description Update an existing consent version by id
     */
    patch: operations["updateConsentVersion"];
    trace?: never;
  };
  "/consent-data-category": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search consent data categories
     * @description Search and filter consent data categories with multiple criteria
     */
    get: operations["searchConsentDataCategories"];
    put?: never;
    /**
     * Create consent data category
     * @description Create a new consent data category
     */
    post: operations["createConsentDataCategory"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/consent-data-category/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get consent data category by ID
     * @description Retrieve a specific consent data category by its ID
     */
    get: operations["getConsentDataCategory"];
    put?: never;
    post?: never;
    /**
     * Delete consent data category
     * @description Delete a consent data category by its ID
     */
    delete: operations["deleteConsentDataCategory"];
    options?: never;
    head?: never;
    /**
     * Update consent data category
     * @description Update an existing consent data category
     */
    patch: operations["updateConsentDataCategory"];
    trace?: never;
  };
  "/consent-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search consent logs
     * @description Search and filter consent logs with multiple criteria
     */
    get: operations["searchConsentLogs"];
    put?: never;
    /**
     * Create consent log
     * @description Create a new consent log
     */
    post: operations["createConsentLog"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/consent-log/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get consent log by ID
     * @description Retrieve a specific consent log by id
     */
    get: operations["getConsentLog"];
    put?: never;
    post?: never;
    /**
     * Delete consent log
     * @description Delete a consent log by id
     */
    delete: operations["deleteConsentLog"];
    options?: never;
    head?: never;
    /**
     * Update consent log
     * @description Update an existing consent log
     */
    patch: operations["updateConsentLog"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Format: uuid
     * @example 550e8400-e29b-41d4-a716-446655440000
     */
    UUID: string;
    /**
     * @description Short string for names, identifiers, and small text fields (max 255 characters)
     * @example analytics
     */
    ShortString: string;
    /**
     * @description Medium string for URLs, emails, and short descriptions (max 512 characters)
     * @example https://example.com/resource
     */
    MediumString: string;
    /**
     * Format: date-time
     * @description Timestamp when the entity was created
     * @example 2024-01-01T00:00:00Z
     */
    CreatedAt: string;
    /**
     * Format: date-time
     * @description Timestamp when the entity was last updated
     * @example 2024-01-01T00:00:00Z
     */
    UpdatedAt: string;
    DataProcessor: {
      /** @description ID of the data processor */
      id?: components["schemas"]["UUID"];
      /** @description Data processor name */
      name?: components["schemas"]["ShortString"];
      /** @description Controller ID of the data processor */
      controller_id?: components["schemas"]["UUID"];
      /** @description Contact information of the data processor */
      contact_info?: components["schemas"]["MediumString"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    Pagination: {
      /** @example 1 */
      page?: number;
      /** @example 10 */
      page_size?: number;
      /** @example 100 */
      total_count?: number;
    };
    DataProcessorListResponse: {
      /** @description List of data processors */
      data_processors?: components["schemas"]["DataProcessor"][];
      pagination?: components["schemas"]["Pagination"];
    };
    /** @enum {string} */
    ErrorCode:
      | "success"
      | "canceled"
      | "unknown"
      | "invalid_argument"
      | "deadline_exceeded"
      | "not_found"
      | "already_exists"
      | "permission_denied"
      | "resource_exhausted"
      | "failed_precondition"
      | "aborted"
      | "out_of_range"
      | "unimplemented"
      | "internal_error"
      | "unavailable"
      | "data_loss"
      | "unauthenticated";
    DataProcessorCreateRequest: {
      /**
       * @description Data processor name
       * @example DataNest, telco, FI
       */
      name: components["schemas"]["ShortString"];
      /** @description Controller ID of the data processor */
      controller_id: components["schemas"]["UUID"];
      /**
       * @description Contact information of the data processor
       * @example company@gmail.com, +84-123-45678
       */
      contact_info: components["schemas"]["MediumString"];
    };
    SuccessResponse: {
      /** @example true */
      success: boolean;
      /** @example Operation completed successfully */
      message: string;
    };
    DataProcessorUpdateRequest: {
      /** @description Data processor name */
      name?: components["schemas"]["ShortString"];
      /** @description Controller ID of the data processor */
      controller_id?: components["schemas"]["UUID"];
      /**
       * @description Data processor contact
       * @example email@datanest.com, +84-123-45678
       */
      contact_info?: components["schemas"]["MediumString"];
    };
    DataController: {
      /** @description ID of the data controller */
      id?: components["schemas"]["UUID"];
      /** @description Data controller name */
      name?: components["schemas"]["ShortString"];
      /** @description Data controller contact */
      contact_info?: components["schemas"]["MediumString"];
      /** @description Data controller address */
      address?: components["schemas"]["MediumString"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    DataControllerListResponse: {
      /** @description List of data controllers */
      data_controllers?: components["schemas"]["DataController"][];
      pagination?: components["schemas"]["Pagination"];
    };
    DataControllerCreateRequest: {
      /**
       * @description Data controller name
       * @example DataNest, FI
       */
      name: components["schemas"]["ShortString"];
      /**
       * @description Data controller contact
       * @example email@datanest.com, +84-123-45678
       */
      contact_info: components["schemas"]["MediumString"];
      /**
       * @description Data controller address
       * @example Hanoi, Vietnam
       */
      address: components["schemas"]["MediumString"];
    };
    DataControllerUpdateRequest: {
      /**
       * @description Data controller name
       * @example DataNest, FI
       */
      name?: components["schemas"]["ShortString"];
      /**
       * @description Data controller contact
       * @example email@datanest.com, +84-123-45678
       */
      contact_info?: components["schemas"]["MediumString"];
      /**
       * @description Data controller address
       * @example Hanoi, Vietnam
       */
      address?: components["schemas"]["MediumString"];
    };
    ConsentPurpose: {
      /** @description ID of the consent purpose */
      id?: components["schemas"]["UUID"];
      /** @description Name of the consent purpose */
      name?: components["schemas"]["ShortString"];
      /** @description ID of the data controller */
      controller_id?: components["schemas"]["UUID"];
      /** @description Description of the consent purpose */
      purpose?: components["schemas"]["MediumString"];
      /** @description Retention period in days */
      retention_days?: number;
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    ConsentPurposeListResponse: {
      /** @description List of consent purposes */
      purposes?: components["schemas"]["ConsentPurpose"][];
      pagination?: components["schemas"]["Pagination"];
    };
    ConsentPurposeCreateRequest: {
      /** @description Name of the consent purpose */
      name: components["schemas"]["ShortString"];
      /** @description ID of the data controller */
      controller_id: components["schemas"]["UUID"];
      /**
       * @description Description of the consent purpose
       * @example tracking
       */
      purpose: components["schemas"]["MediumString"];
      /** @description Retention period in days */
      retention_days: number;
    };
    ConsentPurposeUpdateRequest: {
      /** @description Name of the consent purpose */
      name?: components["schemas"]["ShortString"];
      /** @description ID of the data controller */
      controller_id?: components["schemas"]["UUID"];
      /**
       * @description Description of the consent purpose
       * @example tracking
       */
      purpose?: components["schemas"]["MediumString"];
      /** @description Retention period in days */
      retention_days?: number;
    };
    DataCategory: {
      /** @description ID of the data category */
      id?: components["schemas"]["UUID"];
      /** @description Name of the data category */
      name?: components["schemas"]["ShortString"];
      /** @description Description of the data category */
      description?: components["schemas"]["MediumString"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    DataCategoryListResponse: {
      /** @description List of data categories */
      categories?: components["schemas"]["DataCategory"][];
      pagination?: components["schemas"]["Pagination"];
    };
    DataCategoryCreateRequest: {
      /**
       * @description Name of the data category
       * @example personal_data
       */
      name: components["schemas"]["ShortString"];
      /**
       * @description Description of the data category
       * @example Personal information collected from users
       */
      description: components["schemas"]["MediumString"];
    };
    DataCategoryUpdateRequest: {
      /**
       * @description Name of the data category
       * @example personal_data
       */
      name?: components["schemas"]["ShortString"];
      /**
       * @description Description of the data category
       * @example Personal information collected from users
       */
      description?: components["schemas"]["MediumString"];
    };
    /**
     * @example grant
     * @enum {string}
     */
    ConsentAction: "grant" | "revoke" | "update" | "delete";
    Consent: {
      /** @description ID of the consent */
      id?: components["schemas"]["UUID"];
      /** @description ID of the data controller */
      controller_id?: components["schemas"]["UUID"];
      /** @description ID of the data processor */
      processor_id?: components["schemas"]["UUID"];
      /** @description ID of the lead */
      lead_id?: components["schemas"]["UUID"];
      /** @description ID of the consent version */
      consent_version_id?: components["schemas"]["UUID"];
      /** @description Source of the consent (web, app, sms,...) */
      source?: components["schemas"]["MediumString"];
      /** @description Action performed on the consent */
      action?: components["schemas"]["ConsentAction"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    ConsentListResponse: {
      /** @description List of consents */
      consents?: components["schemas"]["Consent"][];
      pagination?: components["schemas"]["Pagination"];
    };
    ConsentCreateRequest: {
      /** @description ID of the data controller */
      controller_id: components["schemas"]["UUID"];
      /** @description ID of the data processor */
      processor_id: components["schemas"]["UUID"];
      /** @description ID of the lead */
      lead_id: components["schemas"]["UUID"];
      /** @description ID of the consent version */
      consent_version_id: components["schemas"]["UUID"];
      /** @description Source of the consent (web, app, sms,...) */
      source: components["schemas"]["MediumString"];
      /** @description Action performed on the consent */
      action: components["schemas"]["ConsentAction"];
    };
    ConsentUpdateRequest: {
      /** @description ID of the data controller */
      controller_id?: components["schemas"]["UUID"];
      /** @description ID of the data processor */
      processor_id?: components["schemas"]["UUID"];
      /** @description ID of the lead */
      lead_id?: components["schemas"]["UUID"];
      /** @description ID of the consent version */
      consent_version_id?: components["schemas"]["UUID"];
      /** @description Source of the consent (web, app, sms,...) */
      source?: components["schemas"]["MediumString"];
      /** @description Action performed on the consent */
      action?: components["schemas"]["ConsentAction"];
    };
    /**
     * @description Version number
     * @example 1
     */
    VersionField: number;
    /**
     * @description Long string for content, terms, and large text blocks (max 65,535 characters)
     * @example Terms and conditions for data processing...
     */
    LongString: string;
    /**
     * Format: date-time
     * @description Effective date of the entity
     * @example 2024-01-01T00:00:00Z
     */
    EffectiveDateField: string;
    ConsentVersion: {
      /** @description ID of the consent version */
      id?: components["schemas"]["UUID"];
      /** @description ID of the consent purpose */
      consent_purpose_id?: components["schemas"]["UUID"];
      version?: components["schemas"]["VersionField"];
      /** @description Content of the consent version */
      content?: components["schemas"]["LongString"];
      /** @description URL to the consent document */
      document_url?: components["schemas"]["MediumString"];
      /** @description Effective date of the consent version */
      effective_date?: components["schemas"]["EffectiveDateField"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    ConsentVersionListResponse: {
      /** @description List of consent versions */
      consent_versions?: components["schemas"]["ConsentVersion"][];
      pagination?: components["schemas"]["Pagination"];
    };
    ConsentVersionCreateRequest: {
      /** @description ID of the consent purpose */
      consent_purpose_id: components["schemas"]["UUID"];
      version: components["schemas"]["VersionField"];
      /**
       * @description Content of the consent version
       * @example Terms and conditions for data processing
       */
      content: components["schemas"]["LongString"];
      /**
       * @description URL to the consent document
       * @example https://example.com/consent/v1.pdf
       */
      document_url: components["schemas"]["MediumString"];
      /**
       * @description Effective date of the consent version
       * @example 2024-01-01T00:00:00Z
       */
      effective_date: components["schemas"]["EffectiveDateField"];
    };
    ConsentVersionUpdateRequest: {
      /** @description ID of the consent purpose */
      consent_purpose_id?: components["schemas"]["UUID"];
      version?: components["schemas"]["VersionField"];
      /**
       * @description Content of the consent version
       * @example Terms and conditions for data processing
       */
      content?: components["schemas"]["LongString"];
      /**
       * @description URL to the consent document
       * @example https://example.com/consent/v1.pdf
       */
      document_url?: components["schemas"]["MediumString"];
      /**
       * @description Effective date of the consent version
       * @example 2024-02-01T00:00:00Z
       */
      effective_date?: components["schemas"]["EffectiveDateField"];
    };
    ConsentDataCategory: {
      /** @description ID of the consent data category */
      id?: components["schemas"]["UUID"];
      /** @description ID of the consent */
      consent_id?: components["schemas"]["UUID"];
      /** @description ID of the data category */
      data_category_id?: components["schemas"]["UUID"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    ConsentDataCategoryListResponse: {
      /** @description List of consent data categories */
      consent_data_categories?: components["schemas"]["ConsentDataCategory"][];
      pagination?: components["schemas"]["Pagination"];
    };
    ConsentDataCategoryCreateRequest: {
      /** @description ID of the consent */
      consent_id: components["schemas"]["UUID"];
      /** @description ID of the data category */
      data_category_id: components["schemas"]["UUID"];
    };
    ConsentDataCategoryUpdateRequest: {
      /** @description ID of the consent */
      consent_id?: components["schemas"]["UUID"];
      /** @description ID of the data category */
      data_category_id?: components["schemas"]["UUID"];
    };
    ConsentLog: {
      /** @description ID of the consent log */
      id?: components["schemas"]["UUID"];
      /** @description ID of the consent being logged */
      consent_id?: components["schemas"]["UUID"];
      /** @description Action performed on the consent */
      action?: components["schemas"]["ConsentAction"];
      /** @description User or system that performed action */
      action_by?: components["schemas"]["ShortString"];
      /** @description Source of consent action (e.g., web, app, sms,...) */
      source?: components["schemas"]["ShortString"];
      created_at?: components["schemas"]["CreatedAt"];
      updated_at?: components["schemas"]["UpdatedAt"];
    };
    ConsentLogListResponse: {
      /** @description List of consent logs */
      consent_logs?: components["schemas"]["ConsentLog"][];
      pagination?: components["schemas"]["Pagination"];
    };
    ConsentLogCreateRequest: {
      /** @description ID of the consent being logged */
      consent_id: components["schemas"]["UUID"];
      /** @description Action performed on the consent */
      action: components["schemas"]["ConsentAction"];
      /**
       * @description User or system that performed action
       * @example user1
       */
      action_by: components["schemas"]["ShortString"];
      /** @description Source of consent action (e.g., web, app, sms,...) */
      source: components["schemas"]["ShortString"];
    };
    ConsentLogUpdateRequest: {
      /** @description ID of the consent being logged */
      consent_id?: components["schemas"]["UUID"];
      /** @description Action performed on the consent */
      action?: components["schemas"]["ConsentAction"];
      /**
       * @description User or system that performed action
       * @example user1
       */
      action_by?: components["schemas"]["ShortString"];
      /** @description Source of consent action (e.g., web, app, sms,...) */
      source?: components["schemas"]["ShortString"];
    };
  };
  responses: {
    /** @description OK */
    200: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["SuccessResponse"];
      };
    };
    /** @description Bad request */
    400: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          code: components["schemas"]["ErrorCode"];
          message: string;
        };
      };
    };
    /** @description Unauthorized */
    401: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** @example unauthenticated */
          code?: string;
          /** @example Authentication required */
          message?: string;
        };
      };
    };
    /** @description Forbidden */
    403: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** @example permission_denied */
          code?: string;
          /** @example Access denied */
          message?: string;
        };
      };
    };
    /** @description Not Found */
    404: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** @example not_found */
          code?: string;
          /** @example Resource not found */
          message?: string;
        };
      };
    };
    /** @description Internal Server Error */
    500: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** @example internal_error */
          code?: string;
          /** @example Internal server error */
          message?: string;
        };
      };
    };
    /** @description Service Unavailable */
    503: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** @example unavailable */
          code?: string;
          /** @example Service temporarily unavailable */
          message?: string;
        };
      };
    };
    Success: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    InternalServerError: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    ServiceUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
  };
  parameters: {
    /** @description Search term to filter results */
    search: string;
    /** @description Page number for pagination */
    page: number;
    /** @description Number of items per page */
    page_size: number;
    /**
     * @description ID of the resource to retrieve
     * @example 550e8400-e29b-41d4-a716-446655440000
     */
    id: string;
    /** @description Filter by consent action */
    ConsentAction: "grant" | "revoke" | "update" | "delete";
    /** @description Filter by consent id */
    consent_id: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  searchDataProcessors: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of data processors */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataProcessorListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createDataProcessor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataProcessorCreateRequest"];
      };
    };
    responses: {
      /** @description Data processor created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataProcessor"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getDataProcessor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data processor retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataProcessor"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteDataProcessor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateDataProcessor: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataProcessorUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchDataControllers: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of data controllers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataControllerListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createDataController: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataControllerCreateRequest"];
      };
    };
    responses: {
      /** @description Data controller created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataController"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getDataController: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data controller retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataController"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteDataController: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateDataController: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataControllerUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchConsentPurposes: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of consent purposes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentPurposeListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createConsentPurpose: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentPurposeCreateRequest"];
      };
    };
    responses: {
      /** @description Consent purpose created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentPurpose"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getConsentPurpose: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent purpose retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentPurpose"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteConsentPurpose: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateConsentPurpose: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentPurposeUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchDataCategories: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of data categories */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataCategoryListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataCategoryCreateRequest"];
      };
    };
    responses: {
      /** @description Data category created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataCategory"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data category retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataCategory"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DataCategoryUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchConsents: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Filter by consent action */
        action?: components["parameters"]["ConsentAction"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consents search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createConsent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentCreateRequest"];
      };
    };
    responses: {
      /** @description Consent created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Consent"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getConsent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Consent"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteConsent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateConsent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchConsentVersions: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent versions search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentVersionListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createConsentVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentVersionCreateRequest"];
      };
    };
    responses: {
      /** @description Consent version created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentVersion"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getConsentVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent version retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentVersion"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteConsentVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateConsentVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentVersionUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchConsentDataCategories: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent data categories search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentDataCategoryListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createConsentDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentDataCategoryCreateRequest"];
      };
    };
    responses: {
      /** @description Consent data category created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentDataCategory"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getConsentDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent data category retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentDataCategory"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteConsentDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateConsentDataCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentDataCategoryUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  searchConsentLogs: {
    parameters: {
      query?: {
        /** @description Search term to filter results */
        search?: components["parameters"]["search"];
        /** @description Filter by consent id */
        consent_id?: components["parameters"]["consent_id"];
        /** @description Filter by consent action */
        action?: components["parameters"]["ConsentAction"];
        /** @description Page number for pagination */
        page?: components["parameters"]["page"];
        /** @description Number of items per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent logs search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentLogListResponse"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  createConsentLog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentLogCreateRequest"];
      };
    };
    responses: {
      /** @description Consent log created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentLog"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getConsentLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consent log retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConsentLog"];
        };
      };
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  deleteConsentLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  updateConsentLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description ID of the resource to retrieve
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentLogUpdateRequest"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      400: components["responses"]["400"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
}
