/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/flows/{tenant}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tenant onboarding flow */
    get: operations["get-tenant-flow"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new lead */
    post: operations["create-lead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leads/{id}/submit-info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit lead info */
    post: operations["submit-info"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leads/{id}/submit-otp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit OTP for lead */
    post: operations["submit-otp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leads/{id}/resend-otp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend OTP for lead */
    post: operations["resend-otp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leads/{id}/ekyc/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** end point to get ekyc config */
    get: operations["get-ekyc-config"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leads/{id}/ekyc/vnpt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** end point to submit ekyc data from vnpt */
    post: operations["submit-vnpt-ekyc-result"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/locations/provinces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all provinces
     * @description Retrieve a list of all provinces in Vietnam
     */
    get: operations["getProvinces"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/locations/provinces/{id}/wards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get wards by province ID
     * @description Retrieve all wards/communes for a specific province
     */
    get: operations["getWardsByProvinceId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Format: uuid */
    uuid: string;
    /**
     * @description The status of the flow
     * @enum {string}
     */
    FlowStatus: "active" | "inactive" | "archived";
    Step: {
      id: components["schemas"]["uuid"];
      /** @default false */
      use_ekyc: boolean;
      /** @default false */
      send_otp: boolean;
      consent_purpose_id?: components["schemas"]["uuid"];
      /** @default  */
      page: string;
      /** @default false */
      have_purpose: boolean;
      /** @default false */
      required_purpose: boolean;
      /** @default false */
      have_phone_number: boolean;
      /** @default false */
      required_phone_number: boolean;
      /** @default false */
      have_email: boolean;
      /** @default false */
      required_email: boolean;
      /** @default false */
      have_full_name: boolean;
      /** @default false */
      required_full_name: boolean;
      /** @default false */
      have_national_id: boolean;
      /** @default false */
      required_national_id: boolean;
      /** @default false */
      have_second_national_id: boolean;
      /** @default false */
      required_second_national_id: boolean;
      /** @default false */
      have_gender: boolean;
      /** @default false */
      required_gender: boolean;
      /** @default false */
      have_location: boolean;
      /** @default false */
      required_location: boolean;
      /** @default false */
      have_birthday: boolean;
      /** @default false */
      required_birthday: boolean;
      /** @default false */
      have_income_type: boolean;
      /** @default false */
      required_income_type: boolean;
      /** @default false */
      have_income: boolean;
      /** @default false */
      required_income: boolean;
      /** @default false */
      have_having_loan: boolean;
      /** @default false */
      required_having_loan: boolean;
      /** @default false */
      have_career_status: boolean;
      /** @default false */
      required_career_status: boolean;
      /** @default false */
      have_career_type: boolean;
      /** @default false */
      required_career_type: boolean;
      /** @default false */
      have_credit_status: boolean;
      /** @default false */
      required_credit_status: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @description Get Flow by tenant response */
    FlowDetail: {
      id: components["schemas"]["uuid"];
      name: string;
      description: string;
      flow_status: components["schemas"]["FlowStatus"];
      steps: components["schemas"]["Step"][];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @enum {string} */
    OTPType: "sms" | "email" | "voice";
    /** @enum {string} */
    Gender: "male" | "female" | "other";
    /** @enum {string} */
    HavingLoan:
      | "no_loan"
      | "one_loan"
      | "two_loans"
      | "three_loans"
      | "more_than_three_loans";
    /** @enum {string} */
    CareerStatus:
      | "employed"
      | "self_employed"
      | "unemployed"
      | "housewife"
      | "retired";
    /** @enum {string} */
    CreditStatus: "no_bad_debt" | "bad_debt" | "bad_debt_last3_year";
    SubmitLeadInfoRequestBody: {
      flow_id: components["schemas"]["uuid"];
      step_id: components["schemas"]["uuid"];
      phone_number?: string;
      /** Format: email */
      email?: string;
      purpose?: string;
      /** Format: int32 */
      loan_amount?: number;
      /** Format: int32 */
      loan_period?: number;
      otp_type?: components["schemas"]["OTPType"];
      full_name?: string;
      national_id?: string;
      gender?: components["schemas"]["Gender"];
      location?: components["schemas"]["uuid"];
      /** Format: date */
      birthday?: string;
      income_type?: string;
      /** Format: int32 */
      income?: number;
      having_loan?: components["schemas"]["HavingLoan"];
      career_status?: components["schemas"]["CareerStatus"];
      career_type?: string;
      credit_status?: components["schemas"]["CreditStatus"];
    };
    CreateLeadRequestBody: {
      flow_id: components["schemas"]["uuid"];
      consent_id: components["schemas"]["uuid"];
      tenant: components["schemas"]["uuid"];
      deviece_info: Record<string, never>;
      tracking_params: Record<string, never>;
      info: components["schemas"]["SubmitLeadInfoRequestBody"];
    };
    CreateLeadResponseBody: {
      id: components["schemas"]["uuid"];
      token: string;
    };
    SubmitOTPRequestBody: {
      /** @description The token to submit OTP */
      token: string;
      /** @description The OTP code received */
      otp: string;
    };
    ResendOTPRequestBody: {
      /** @description The phone number or email to resend OTP */
      target: string;
    };
    /**
     * @description ekyc sdk flow
     * @enum {string}
     */
    SdkFlow: "DOCUMENT_TO_FACE" | "FACE_TO_DOCUMENT" | "FACE" | "DOCUMENT";
    /**
     * @description ekyc picture method
     * @enum {string}
     */
    PictureMethod: "BOTH" | "PHOTO" | "UPLOAD";
    EkycConfigResponseBody: {
      access_token: string;
      challenge_code: string;
      has_result_screen: boolean;
      enable_api_liveness_document: boolean;
      enable_api_liveness_face: boolean;
      enable_api_masked_face: boolean;
      enable_api_compare_face: boolean;
      sdk_flow: components["schemas"]["SdkFlow"];
      list_type_document: number[];
      show_step: boolean;
      has_qr_scan: boolean;
      /** Format: int32 */
      document_type_start: number;
      double_liveness: boolean;
      use_method: components["schemas"]["PictureMethod"];
      show_tab_result_information: boolean;
      show_tab_result_validation: boolean;
      show_tab_result_qrcode: boolean;
    };
    VNPTLivenessCard: {
      challengeCode: string;
      dataBase64: string;
      dataSign: string;
      imgs: {
        img: string;
      };
      logID: string;
      message: string;
      object: {
        face_swapping: string;
        /** Format: double */
        face_swapping_prob: number;
        fake_liveness: string;
        /** Format: double */
        fake_liveness_prob: number;
        fake_print_photo: string;
        /** Format: double */
        fake_print_photo_prob: number;
        liveness: string;
        liveness_msg: string;
      };
      server_version: string;
      statusCode: number;
    };
    VnptEkycCheckingOcrResult: {
      /** Format: double */
      check_photocopied_prob: number;
      check_photocopied_result: string;
      corner_cut_prob: number[];
      corner_cut_result: string;
      /** Format: double */
      edited_prob: number;
      edited_result: string;
      /** Format: double */
      recaptured_prob: number;
      recaptured_result: string;
    };
    VnptEkycOcrPostCode: {
      city: unknown[];
      detail: string;
      district: unknown[];
      type: string;
      ward: unknown[];
    };
    VnptEkycOrcQuality: {
      /** Format: double */
      blur_score: number;
      bright_spot_params: {
        /** Format: double */
        average_intensity: number;
        /** Format: double */
        bright_spot_threshold: number;
        total_bright_spot_area: number;
      };
      /** Format: double */
      bright_spot_score: number;
      final_result: {
        bad_luminance_likelyhood: string;
        blurred_likelyhood: string;
        bright_spot_likelyhood: string;
        low_resolution_likelyhood: string;
      };
      /** Format: double */
      luminance_score: number;
      resolution: number[];
    };
    VNPTOCR: {
      message: string;
      challengeCode: string;
      dataBase64: string;
      dataSign: string;
      imgs: {
        img_back?: string;
        img_front?: string;
      };
      logID: string;
      object: {
        address_fake_warning?: boolean;
        back_corner_warning?: string;
        back_expired_warning?: string;
        /** Format: int32 */
        back_type_id?: number;
        birth_day?: string;
        /** Format: double */
        birth_day_prob?: number;
        card_type?: string;
        checking_result_back?: components["schemas"]["VnptEkycCheckingOcrResult"];
        checking_result_front?: components["schemas"]["VnptEkycCheckingOcrResult"];
        citizen_id?: string;
        /** Format: double */
        citizen_id_prob?: number;
        corner_warning?: string;
        /** Format: double */
        cover_prob_front?: number;
        dict_qr?: Record<string, never>;
        dob_fake_warning?: boolean;
        /** Format: double */
        dob_fake_warning_prob?: number;
        dupplication_warning?: boolean;
        expire_warning?: string;
        features?: string;
        /** Format: double */
        features_prob?: number;
        gender?: string;
        general_warning?: unknown[];
        id?: string;
        /** Format: double */
        id_fake_prob?: number;
        id_fake_warning?: string;
        id_probs?: number[];
        issue_date?: string;
        /** Format: double */
        issue_date_prob?: number;
        issue_date_probs?: number[];
        issue_place?: string;
        /** Format: double */
        issue_place_prob?: number;
        issuedate_fake_warning?: boolean;
        match_front_back?: {
          match_bod?: string;
          match_id?: string;
          match_name?: string;
          match_sex?: string;
          match_valid_date?: string;
        };
        match_qr?: Record<string, never>;
        mrz?: string[];
        /** Format: double */
        mrz_prob?: number;
        mrz_probs?: number[];
        mrz_valid_score?: number;
        msg?: string;
        msg_back?: string;
        name?: string;
        name_fake_warning?: string;
        /** Format: double */
        name_fake_warning_prob?: number;
        /** Format: double */
        name_prob?: number;
        name_probs?: number[];
        nation_policy?: string;
        nationality?: string;
        new_post_code?: components["schemas"]["VnptEkycOcrPostCode"][];
        origin_location?: string;
        /** Format: double */
        origin_location_prob?: number;
        post_code?: components["schemas"]["VnptEkycOcrPostCode"][];
        quality_back?: components["schemas"]["VnptEkycOrcQuality"];
        quality_front?: components["schemas"]["VnptEkycOrcQuality"];
        recent_location?: string;
        /** Format: double */
        recent_location_prob?: number;
        tampering?: {
          is_legal: string;
          warning: string[];
        };
        type_id?: number;
        valid_date?: string;
        /** Format: double */
        valid_date_prob?: number;
      };
      server_version: string;
      statusCode: number;
    };
    VNPTLivenessFace: {
      challengeCode: string;
      dataBase64: string;
      dataSign: string;
      imgs: {
        img_face: string;
        img_front: string;
      };
      object: {
        /** Format: int32 */
        age: number;
        background_warning: string;
        blur_face: string;
        /** Format: double */
        blur_face_prob: number;
        gender: string;
        is_eye_open: string;
        liveness: string;
        liveness_msg: string;
        /** Format: double */
        liveness_prob: number;
        multiple_faces_detail: {
          multiple_face_1: boolean;
          multiple_face_2: boolean;
        };
      };
      server_version: string;
      message: string;
      logID: string;
      statusCode: number;
    };
    VNPTMasked: {
      challengeCode: string;
      dataBase64: string;
      dataSign: string;
      imgs: {
        img: string;
      };
      message: string;
      object: {
        masked?: string;
      };
      server_version: string;
      statusCode: number;
    };
    VNPTCompare: {
      challengeCode: string;
      dataBase64: string;
      dataSign: string;
      imgs: {
        img_face: string;
        img_front: string;
      };
      object: {
        match_warning: string;
        msg: string;
        multiple_faces: boolean;
        multiple_faces_detail: {
          multiple_face_1: boolean;
          multiple_face_2: boolean;
        };
        /** Format: double */
        prob: number;
        result: string;
      };
      server_version: string;
      message: string;
      logID: string;
      statusCode: number;
    };
    VNPTBase64DocImg: {
      img_front: string;
      img_back: string;
    };
    VNPTBase64FaceImg: {
      img_face_far: string;
      img_face_near: string;
    };
    VNPTHashDocument: {
      img_back: string;
      img_front: string;
    };
    VnptEkycRequestBody: {
      type_document?: number;
      liveness_card_front?: components["schemas"]["VNPTLivenessCard"];
      liveness_card_back?: components["schemas"]["VNPTLivenessCard"];
      ocr?: components["schemas"]["VNPTOCR"];
      liveness_face?: components["schemas"]["VNPTLivenessFace"];
      masked?: components["schemas"]["VNPTMasked"];
      hash_img?: string;
      compare?: components["schemas"]["VNPTCompare"];
      base64_doc_img?: components["schemas"]["VNPTBase64DocImg"];
      base64_face_img?: components["schemas"]["VNPTBase64FaceImg"];
      data_hash_document?: components["schemas"]["VNPTHashDocument"];
      qr_code?: string;
    };
    Province: {
      /**
       * Format: uuid
       * @description Unique identifier for the province
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /**
       * @description Province code
       * @example 01
       */
      code: string;
      /**
       * @description Province name in Vietnamese
       * @example Hà Nội
       */
      name: string;
      /**
       * @description Province name in English
       * @example Ha Noi
       */
      name_en?: string;
      /**
       * @description Full province name in Vietnamese
       * @example Thành phố Hà Nội
       */
      full_name?: string;
      /**
       * @description Full province name in English
       * @example Ha Noi City
       */
      full_name_en?: string;
      /**
       * @description Province code name (slug)
       * @example ha_noi
       */
      code_name?: string;
      /**
       * Format: date-time
       * @description Timestamp when the province was created
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description Timestamp when the province was last updated
       */
      updated_at?: string;
    };
    Ward: {
      /**
       * Format: uuid
       * @description Unique identifier for the ward
       * @example 660e8400-e29b-41d4-a716-446655440001
       */
      id: string;
      /**
       * @description Ward code
       * @example 00004
       */
      code: string;
      /**
       * @description Ward name in Vietnamese
       * @example Ba Đình
       */
      name: string;
      /**
       * @description Ward name in English
       * @example Ba Dinh
       */
      name_en?: string;
      /**
       * @description Full ward name in Vietnamese
       * @example Phường Ba Đình
       */
      full_name?: string;
      /**
       * @description Full ward name in English
       * @example Ba Dinh Ward
       */
      full_name_en?: string;
      /**
       * @description Ward code name (slug)
       * @example ba_dinh
       */
      code_name?: string;
      /**
       * @description Code of the province this ward belongs to
       * @example 01
       */
      province_code: string;
      /**
       * Format: date-time
       * @description Timestamp when the ward was created
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description Timestamp when the ward was last updated
       */
      updated_at?: string;
    };
    /** @enum {string} */
    ErrorCode:
      | "success"
      | "canceled"
      | "unknown"
      | "invalid_argument"
      | "deadline_exceeded"
      | "not_found"
      | "already_exists"
      | "permission_denied"
      | "resource_exhausted"
      | "failed_precondition"
      | "aborted"
      | "out_of_range"
      | "unimplemented"
      | "internal_error"
      | "unavailable"
      | "data_loss"
      | "unauthenticated";
  };
  responses: {
    /** @description OK */
    200: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Bad request */
    400: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          code: components["schemas"]["ErrorCode"];
          message: string;
        };
      };
    };
    /** @description Unauthorized */
    401: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Forbidden */
    403: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Not Found */
    404: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Internal Server Error */
    500: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Service Unavailable */
    503: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
  };
  parameters: {
    /** @description Tenant */
    tenant: string;
    /** @description uuid id */
    id: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "get-tenant-flow": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Tenant */
        tenant: components["parameters"]["tenant"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlowDetail"];
        };
      };
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  "create-lead": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLeadRequestBody"];
      };
    };
    responses: {
      /** @description success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateLeadResponseBody"];
        };
      };
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  "submit-info": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description uuid id */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitLeadInfoRequestBody"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  "submit-otp": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description uuid id */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitOTPRequestBody"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  "resend-otp": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description uuid id */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendOTPRequestBody"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  "get-ekyc-config": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description uuid id */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description get ekyc access key successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EkycConfigResponseBody"];
        };
      };
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  "submit-vnpt-ekyc-result": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description uuid id */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VnptEkycRequestBody"];
      };
    };
    responses: {
      200: components["responses"]["200"];
      401: components["responses"]["401"];
      403: components["responses"]["403"];
      500: components["responses"]["500"];
      503: components["responses"]["503"];
    };
  };
  getProvinces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successfully retrieved provinces */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Province"][];
          };
        };
      };
      500: components["responses"]["500"];
    };
  };
  getWardsByProvinceId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Province ID (UUID) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successfully retrieved wards */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Ward"][];
          };
        };
      };
      400: components["responses"]["400"];
      404: components["responses"]["404"];
      500: components["responses"]["500"];
    };
  };
}
