import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { NextIntlClientProvider } from "next-intl";

// @ts-expect-error
import "../globals.css";

import LanguageSwitcher from "@/components/language-switcher";
import Providers from "@/components/layout/providers";
import { ThemeSelector } from "@/components/theme/theme-selector";

export function generateStaticParams() {
  return [{ locale: "vi" }, { locale: "en" }];
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            {children}
            <div className="fixed bottom-5 left-5 z-50">
              <ThemeSelector />
            </div>
            <div className="fixed bottom-5 right-5 z-50">
              <LanguageSwitcher />
            </div>
          </Providers>
        </NextIntlClientProvider>
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.7.4/lottie.min.js"
          strategy="beforeInteractive"
        />
        <Script
          id="oval_custom"
          src="/vendor/VNPTBrowserSDKAppV4.0.0.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/vendor/VNPTQRBrowserApp.js"
          strategy="beforeInteractive"
        />
        <Script src="/vendor/VNPTQRUpload.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
