import { renderHook, waitFor } from "@testing-library/react";
import * as fc from "fast-check";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import * as cookieUtils from "@/lib/utils/cookie";
import {
  clearConsentSessionCookie,
  useConsentSession,
} from "../use-consent-session";

/**
 * Property-Based Tests for Session Manager
 *
 * Feature: migrate-consent-storage-to-cookies
 *
 * These tests validate universal correctness properties across randomly
 * generated inputs using fast-check library. Each property is tested with
 * 100+ iterations to ensure robustness.
 */

describe("Session Manager - Property-Based Tests", () => {
  let cookieStore: Record<string, string> = {};

  beforeEach(() => {
    // Reset cookie store
    cookieStore = {};

    // Mock document.cookie
    Object.defineProperty(document, "cookie", {
      get: () => {
        return Object.entries(cookieStore)
          .map(([name, value]) => `${name}=${value}`)
          .join("; ");
      },
      set: (cookieString: string) => {
        const [nameValue] = cookieString.split(";");
        const [name, value] = nameValue.split("=");

        if (name && value !== undefined) {
          const isDelete =
            cookieString.includes("max-age=0") ||
            cookieString.includes("max-age=-");

          if (isDelete) {
            delete cookieStore[name.trim()];
          } else {
            cookieStore[name.trim()] = value;
          }
        }
      },
      configurable: true,
    });

    // Clear module-level cache
    clearConsentSessionCookie();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  /**
   * Property 1: Session ID Round-Trip Preservation
   *
   * **Validates: Requirements 1.8**
   *
   * For any valid UUID v4 session ID, storing it via the Session Manager
   * and then retrieving it SHALL return the same session ID value.
   *
   * This property ensures that the cookie storage mechanism correctly
   * preserves session ID values without corruption or data loss.
   */
  it("Property 1: Session ID round-trip preservation", async () => {
    // Feature: migrate-consent-storage-to-cookies, Property 1: Session ID round-trip preservation

    await fc.assert(
      fc.asyncProperty(fc.uuid(), async (sessionId) => {
        // Clear any previous state
        clearConsentSessionCookie();
        cookieStore = {};

        // Store the session ID in cookie
        const storeSuccess = cookieUtils.setCookie(
          "consent_session_id",
          sessionId,
          {
            maxAge: 2592000,
            secure: true,
            sameSite: "Lax",
            path: "/",
          },
        );

        // Verify cookie write succeeded
        expect(storeSuccess).toBe(true);

        // Retrieve the session ID using the hook
        const { result } = renderHook(() => useConsentSession());

        // Wait for the hook to initialize
        await waitFor(
          () => {
            expect(result.current).not.toBeNull();
          },
          { timeout: 1000 },
        );

        // Verify round-trip: retrieved value matches stored value
        expect(result.current).toBe(sessionId);
      }),
      {
        numRuns: 100,
        verbose: true,
      },
    );
  });

  /**
   * Property 4: UUID Format Validation
   *
   * **Validates: Requirements 5.3**
   *
   * For any session ID generated by the Session Manager, the value SHALL
   * conform to the UUID v4 specification format (8-4-4-4-12 hexadecimal
   * pattern with version and variant bits correctly set).
   *
   * This property ensures that session IDs are cryptographically secure
   * and properly formatted. UUID v4 uses random generation, providing
   * sufficient entropy for unique session identification while meeting
   * GDPR requirements for secure identifiers.
   *
   * **UUID v4 Format Requirements:**
   * - Pattern: 8-4-4-4-12 hexadecimal digits (xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx)
   * - Version bits: 13th hex digit must be '4' (version 4)
   * - Variant bits: 17th hex digit must be one of [8, 9, a, b] (RFC 4122 variant)
   */
  it("Property 4: UUID format validation", async () => {
    // Feature: migrate-consent-storage-to-cookies, Property 4: UUID format validation

    // UUID v4 regex pattern:
    // - 8 hex digits, hyphen
    // - 4 hex digits, hyphen
    // - '4' followed by 3 hex digits (version 4), hyphen
    // - One of [8,9,a,b] followed by 3 hex digits (variant bits), hyphen
    // - 12 hex digits
    const uuidV4Pattern =
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

    await fc.assert(
      fc.asyncProperty(fc.constant(null), async () => {
        // Clear any previous state to force new session ID generation
        clearConsentSessionCookie();
        cookieStore = {};

        // Generate a new session ID using the hook
        const { result } = renderHook(() => useConsentSession());

        // Wait for the hook to generate and return a session ID
        await waitFor(
          () => {
            expect(result.current).not.toBeNull();
          },
          { timeout: 1000 },
        );

        const sessionId = result.current;

        // Verify session ID is not null
        expect(sessionId).not.toBeNull();

        // Verify UUID v4 format: 8-4-4-4-12 hexadecimal pattern
        expect(sessionId).toMatch(uuidV4Pattern);

        // Additional validation: verify version bits (13th hex digit = '4')
        const versionDigit = sessionId![14]; // Position 14 in string (after 8 chars + hyphen + 4 chars + hyphen)
        expect(versionDigit).toBe("4");

        // Additional validation: verify variant bits (17th hex digit = 8, 9, a, or b)
        const variantDigit = sessionId![19].toLowerCase(); // Position 19 in string
        expect(["8", "9", "a", "b"]).toContain(variantDigit);
      }),
      {
        numRuns: 100,
        verbose: true,
      },
    );
  });
});
